
CP := -cp ./target/lista-1.0-SNAPSHOT.jar


velha: 
	mvn package && java $(CP) uern.oop.velha.Main

escola:
	mvn package && java $(CP) uern.oop.escola.Main

baralho:
	mvn package && java $(CP) uern.oop.baralho.Main
baralho_run:
	java $(CP) uern.oop.baralho.Main

